# Configuration principale
AllCops:
  # @see https://docs.rubocop.org/rubocop/configuration.html#pre-processing
  Exclude:
  
    - .DS_Store
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-main-config-rubocop-performance-yml
  
    - .rubocop-https---raw-githubusercontent-com-sashite-sashite-rubocop-rb-main-config-rubocop-yml
  
    - .yardoc/
  
    - coverage/
  
    - doc/
  
    - lib/.DS_Store
  
    - lib/feen/.DS_Store
  
    - lib/feen/dumper/.DS_Store
  
    - lib/feen/parser/.DS_Store
  
    - pkg/
  
    - test/.DS_Store
  
    - test/feen/.DS_Store
  
    - tmp/
  
    - test.rb
    - config/**/*
    - tmp/**/*
    - spec/**/*
  NewCops: enable
  TargetRubyVersion: 3.2

# Plugins
plugins:
  - rubocop-performance
  - rubocop-rake

inherit_from:
  - .rubocop_todo.yml

# Layout
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - README.md
  Include:
    - app/**/*
    - config/**/*
    - test/**/*

# Lint
Lint/ConstantResolution:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Naming
Naming/ConstantName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/MethodName:
  Enabled: false

# Style
Style/ClassAndModuleChildren:
  EnforcedStyle: nested

# Check with yard instead.
Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantConstantBase:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

# As long as we don't need to use a version lower or equal to 1.9, we can use the new syntax.
Style/SymbolArray:
  Enabled: true
