require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

  Exclude:
    - test/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

Style/AsciiComments:
  Exclude:
    - lib/**/*
    - README.md

Layout/LineLength:
  Exclude:
    - lib/**/*
